version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - aeropuertos-net

  redis-geo:
    image: redis:6.2
    container_name: redis-geo
    command: redis-server --save "" --appendonly no
    networks:
      - aeropuertos-net

  redis-pop:
    image: redis:6.2
    container_name: redis-pop
    command: redis-server --save "" --appendonly no
    networks:
      - aeropuertos-net

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_GEO_HOST=redis-geo
      - REDIS_POP_HOST=redis-pop
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis-geo
      - redis-pop
    networks:
      - aeropuertos-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - aeropuertos-net

volumes:
  mongo_data:

networks:
  aeropuertos-net:
    name: aeropuertos-net
    driver: bridge